site_name: Moje projekty
site_author: Piotr Bednarski
site_description: >-
    Portfolio moich projekt√≥w z Data Science, AI i ML

repo_name: piobpc/portfolio
repo_url: https://github.com/piobpc/portfolio

theme:
  name: material

nav:
- Strona Domowa: index.md
#- Obecny projekt:
- Zrealizowane projekty:
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md